name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
      - deploy-setup
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p deploy-package
          # Copy package.json to root for Azure to recognize it
          cp package*.json deploy-package/
          # Copy backend directory
          cp -r backend deploy-package/
          # Copy built frontend as frontend-dist
          cp -r frontend/dist deploy-package/frontend-dist
          # Create a simple startup script for Azure
          echo "node backend/server.js" > deploy-package/startup.sh
          chmod +x deploy-package/startup.sh
          ls -la deploy-package/
          echo "Contents of deploy-package:"
          find deploy-package -type f

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'livesport-1754580022'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
